version: '2.2'
networks:
  reverse-proxy:
    name: ${REVERSE_PROXY_NETWORK_NAME}
    external: true
services:
  deluge-web:
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:deluge.${STEALTHBOX_DOMAIN}'
      - traefik.port=80
    networks:
      - default
      - reverse-proxy
  medusa:
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:medusa.${STEALTHBOX_DOMAIN}'
      - traefik.port=80
    networks:
      - default
      - reverse-proxy
  couchpotato:
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:couchpotato.${STEALTHBOX_DOMAIN}'
      - traefik.port=80
    networks:
      - default
      - reverse-proxy
  headphones:
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:headphones.${STEALTHBOX_DOMAIN}'
      - traefik.port=80
    networks:
      - default
      - reverse-proxy
